2024-11-26 09:14:11,738 DEBUG    root            Loaded Command Group: ['gcloud', 'projects']
2024-11-26 09:14:11,778 DEBUG    root            Loaded Command Group: ['gcloud', 'projects', 'add_iam_policy_binding']
2024-11-26 09:14:11,793 DEBUG    root            Running [gcloud.projects.add-iam-policy-binding] with arguments: [--member: "serviceAccount:644941739395-compute@developer.gserviceaccount.com", --role: "roles/iam.roleAdmin", PROJECT_ID: "inspired-photon-441609-k7"]
2024-11-26 09:14:11,845 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2024-11-26 09:14:12,024 DEBUG    urllib3.connectionpool https://cloudresourcemanager.googleapis.com:443 "POST /v1/projects/inspired-photon-441609-k7:getIamPolicy?alt=json HTTP/1.1" 200 None
2024-11-26 09:14:12,060 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2024-11-26 09:14:12,507 DEBUG    urllib3.connectionpool https://cloudresourcemanager.googleapis.com:443 "POST /v1/projects/inspired-photon-441609-k7:setIamPolicy?alt=json HTTP/1.1" 403 None
2024-11-26 09:14:12,517 DEBUG    root            (gcloud.projects.add-iam-policy-binding) [644941739395-compute@developer.gserviceaccount.com] does not have permission to access projects instance [inspired-photon-441609-k7:setIamPolicy] (or it may not exist): Policy update access denied. This command is authenticated as 644941739395-compute@developer.gserviceaccount.com which is the active account specified by the [core/account] property.
Traceback (most recent call last):
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/calliope/cli.py", line 998, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/calliope/backend.py", line 843, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/command_lib/util/apis/yaml_command_translator.py", line 1375, in Run
    ref, response = self._CommonRun(args)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/command_lib/util/apis/yaml_command_translator.py", line 455, in _CommonRun
    response = method.Call(
               ^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/command_lib/util/apis/registry.py", line 341, in Call
    return request_func(global_params=global_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/command_lib/util/apis/registry.py", line 404, in RequestFunc
    return method(request, global_params=global_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/generated_clients/apis/cloudresourcemanager/v1/cloudresourcemanager_v1_client.py", line 966, in SetIamPolicy
    return self._RunMethod(
           ^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/third_party/apitools/base/py/base_api.py", line 747, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/third_party/apitools/base/py/base_api.py", line 753, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/third_party/apitools/base/py/base_api.py", line 612, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpForbiddenError: HttpError accessing <https://cloudresourcemanager.googleapis.com/v1/projects/inspired-photon-441609-k7:setIamPolicy?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Tue, 26 Nov 2024 09:14:12 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'server-timing': 'gfet4t7; dur=406', 'transfer-encoding': 'chunked', 'status': 403}>, content <{
  "error": {
    "code": 403,
    "message": "Policy update access denied.",
    "status": "PERMISSION_DENIED"
  }
}
>
2024-11-26 09:14:12,520 ERROR    root            (gcloud.projects.add-iam-policy-binding) [644941739395-compute@developer.gserviceaccount.com] does not have permission to access projects instance [inspired-photon-441609-k7:setIamPolicy] (or it may not exist): Policy update access denied. This command is authenticated as 644941739395-compute@developer.gserviceaccount.com which is the active account specified by the [core/account] property.
